databases:
  - name: pitcrew-connect-db
    plan: free

services:
  - type: web
    name: pitcrew-connect
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pitcrew-connect-db
          property: connectionString
